#!/usr/bin/perl -w
# I don't know much about Perl, so this probably sucks.
# Author: Laurent Bachelier <laurent@bachelier.name>
# Based on: urxvt-perls by Bert Muennich
# License:  GPLv2

use strict;

my $matcher = qr{(\x{00A0})}x;

sub on_start {
    my ($self) = @_;
    $self->enable(line_update => \&line_update);

    ()
}

sub line_update {
    my ($self, $row) = @_;

    my $line = $self->line($row);
    my $text = $line->t;
    my $rend = $line->r;

    while ($text =~ /$matcher/g) {
        my $idx = $-[1];

        @{$rend}[$idx] |= urxvt::SET_BGCOLOR($_, 240);
        $line->r($rend);
    }
    $line->t($text);

    ()
}
